version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/heavens-above"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automation"

