name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies', 'maintenance']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No user-facing changes'
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'feature', 'enhancement']
  patch:
    labels: ['patch', 'fix', 'bug', 'chore', 'dependencies']
  default: patch

