name: CI-Minimal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json || true
          npm install || echo "npm install skipped (no package.json?)"

      - name: Verify environment
        run: |
          node -v
          npm -v
          echo "✅ Basic CI passed successfully."
