name: Release Notes Automation

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: heavens-above

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Notes
        id: notes
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on tag with notes
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.GITHUB_REF_NAME;
            const body = `Release notes for ${tag} are available in the latest release draft.`;
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              body,
              draft: false,
              prerelease: false,
            });

