name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: {}

defaults:
  run:
    working-directory: heavens-above

permissions:
  contents: write
  pull-requests: write

jobs:
  npm-outdated:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: |
          npm ci || npm install

      - name: Audit for vulnerabilities
        run: |
          npm audit --audit-level=high || true

      - name: Create update branch
        run: |
          BRANCH="chore/deps-update-$(date +%Y%m%d)"
          git checkout -b "$BRANCH" || git checkout "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        id: branch

      - name: Update minor/patch dependencies
        run: |
          npm update --save --save-dev || true

      - name: Run tests (if present)
        run: |
          npm test --if-present

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json || true
          git commit -m "chore(deps): weekly dependency updates" || echo "No changes to commit"

      - name: Push branch
        run: |
          git push --set-upstream origin ${{ steps.branch.outputs.branch }} || true

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.branch.outputs.branch }}
          title: "chore(deps): weekly dependency updates"
          body: |
            Automated dependency updates.
            - Ran `npm update` and `npm audit`
            - Please review breaking changes if any
          labels: dependencies, automation
          commit-message: "chore(deps): weekly dependency updates"
          draft: false

