name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: heavens-above

jobs:
  npm-outdated:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect lockfile
        id: lock
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "has_lock=true" >> $GITHUB_OUTPUT
          else
            echo "has_lock=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node (with cache)
        if: steps.lock.outputs.has_lock == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            npm-shrinkwrap.json
            yarn.lock

      - name: Setup Node (no cache)
        if: steps.lock.outputs.has_lock != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Audit for vulnerabilities
        run: |
          npm audit --audit-level=high || true

      - name: Create update branch
        run: |
          BRANCH="chore/deps-update-$(date +%Y%m%d)"
          git checkout -b "$BRANCH" || git checkout "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        id: branch

      - name: Update minor/patch dependencies
        run: |
          npm update --save --save-dev || true

      - name: Run tests (if present)
        run: |
          npm test --if-present

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json || true
          git commit -m "chore(deps): weekly dependency updates" || echo "No changes to commit"

      - name: Push branch
        run: |
          git push --set-upstream origin ${{ steps.branch.outputs.branch }} || true

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.branch.outputs.branch }}
          title: "chore(deps): weekly dependency updates"
          body: |
            Automated dependency updates.
            - Ran `npm update` and `npm audit`
            - Please review breaking changes if any
          labels: dependencies, automation
          commit-message: "chore(deps): weekly dependency updates"
          draft: false

