name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  npm-outdated:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect lockfile
        id: lock
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "has_lock=true" >> $GITHUB_OUTPUT
          else
            echo "has_lock=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node (with cache)
        if: steps.lock.outputs.has_lock == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            npm-shrinkwrap.json
            yarn.lock

      - name: Setup Node (no cache)
        if: steps.lock.outputs.has_lock != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Audit for vulnerabilities
        run: |
          npm audit --audit-level=high || true

      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to branch
        id: branch
        run: |
          BRANCH="chore/deps-update-$(date +%Y%m%d-%H%M%S)"
          git fetch origin
          git checkout -b "$BRANCH" origin/main 2>/dev/null || git checkout "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Branch: $BRANCH"

      - name: Update dependencies
        id: update
        run: |
          echo "📦 Updating dependencies..."
          npm update --save --save-dev || true
          
          # Check if there are changes
          if [ -n "$(git status --porcelain package.json package-lock.json)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "✅ Dependencies were updated"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No dependency updates available"
          fi

      - name: Run tests (if present)
        if: steps.update.outputs.has_changes == 'true'
        run: |
          npm test --if-present || true

      - name: Commit changes
        if: steps.update.outputs.has_changes == 'true'
        run: |
          git add package.json package-lock.json npm-shrinkwrap.json 2>/dev/null || true
          git commit -m "chore(deps): weekly dependency updates

Automated dependency update
- Updated packages to latest minor/patch versions
- Ran tests to verify compatibility
- Review for breaking changes" || echo "⚠️ Nothing to commit"

      - name: Push branch
        if: steps.update.outputs.has_changes == 'true'
        run: |
          git push --set-upstream origin "${{ steps.branch.outputs.branch }}" 2>&1 || git push origin "${{ steps.branch.outputs.branch }}" 2>&1

      - name: Create Pull Request
        if: steps.update.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch.outputs.branch }}
          base: main
          delete-branch: false
          title: "chore(deps): weekly dependency updates"
          body: |
            ## 📦 Automated Dependency Update
            
            This PR contains weekly dependency updates.
            
            ### Changes
            - Updated npm packages to latest minor/patch versions
            - Ran full test suite to verify compatibility
            
            ### Checklist
            - [ ] Review for breaking changes
            - [ ] Check test results
            - [ ] Review security advisories if any
            
            **Note:** Auto-generated by GitHub Actions
          labels: dependencies,automation,dependencies-update
          draft: false
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Summary
        if: always()
        run: |
          echo "## Dependency Update Summary"
          echo "Has changes: ${{ steps.update.outputs.has_changes }}"
          echo "Branch: ${{ steps.branch.outputs.branch }}"
          if [ "${{ steps.update.outputs.has_changes }}" == "true" ]; then
            echo "✅ PR created with dependency updates"
          else
            echo "ℹ️ No updates available at this time"
          fi
